### PR TITLE
New Feed subscription and Popularity Plots

### PR DESCRIPTION
**Pull request by LucvandenBrand**
The plots have been made in Excel, as @DanChirtoaca and I found this tool exported the highest pdf quality (google sheets only exports an image in the pdf).

They are based on the clean data slice uploaded on basecamp.

If all of you are happy with these, we could export all plots using the same style in excel (available at uwp.rug.nl for remote use ;) ).

### CODE REVIEW

**Comment by mircealungu** [comment]
Looks good.

**Comment by mircealungu** [comment]
I still miss a bit the little 'x's instead of diamonds, but in general this looks good!

**Comment by mircealungu** [comment]
what do you mean by: "google sheets only exports an image in the pdf"? png?

**Comment by LucvandenBrand** [comment]
When you export to pdf using google sheets, it simply puts the low-resolution image in a pdf file, which is no better than simply having the png we use already.

**Comment by LucvandenBrand** [comment]
I did the x's, but it turned out to be very hard to see, so I thought this might be better. It can still be changed of course.

**Comment by mircealungu** [comment]
ah, i see!

If the x-s are not good, then let's keep diamonds.
it's cool.

**Pull request merged**
