### PR TITLE
replaced 'Apollo' figures with pdf alternatives

### PR DESCRIPTION
**Pull request by DanChirtoaca**

### CODE REVIEW

**Comment by LucvandenBrand** [comment]
Still two differences in prometheus figures and apollo figures now:
1. We seem to use different font sizes
2. users_articles.pdf uses different gridlines (and less users) than users_feed.pdf, although they represent very similar data

Which font size do you think is better, and does yours look good with similar gridlines?

**Comment by DanChirtoaca** [comment]
I can increase the font size, I did not mess with it, so if you tell me the value you used, I will match that.

What concerns the gridlines, not sure what value they add, but if @mircealungu agrees that they are necessary, I should be able to add them.

The number of students in the users_articles is the number of people that triggered the 'OPEN ARTICLE' event, might that be the reason? In that case, what event do you think would suit better for determining the fact that an article was explored?

**Comment by LucvandenBrand** [comment]
The font is 12pt Calibri, for everything: axis numbers, axis title, labels. The axis title is in bold.
I also omit the main title, as it will be redundant when we add captions in latex.

_Opening_ articles is only measurable with the event, indeed explaining the different sample sizes. We can check for translated articles per-user, but I do not think that information will be more valuable regarding intrest. As long as the paper properly explains how we created these graphs, I think we're fine.

**Comment by mircealungu** [comment]
@DanChirtoaca @Lukeslux - the gridlines look ok on the chart of Luc, but I wonder whether they would not be overkill on the chart of Dan. Could we have a second version of the chart with them? so we see how it looks? One thing that we can do in both the cases, is to reduce a bit more the intensity of gray for the gridlines, make it half as dark as it is now... then even if they're there, they won't disturb. 

how is it possible that we have 80 people registered to feeds and 60 people who opened articles? what did the others do? or did we deploy the logging later, so we don't have information for the entire period?

**Comment by mircealungu** [comment]
and @DanChirtoaca, i like the new charts w/o the 3d much more than before 👍

**Comment by DanChirtoaca** [comment]
Updated the figures.

The logging was indeed deployed later. In that case some students did register for feeds and such but never used the system after the logging was introduced, so the actual usage events for them have never been recorded. I did use the same analysis as before, so I don't think I am missing something, or am I?

**Pull request merged**
